package view;

public enum  MainCommandStatus {
    NO_MAIN_COM,
    //account menu
    VIEW_ACCOUNT_MENU,VIEW_PERSONAL_INFO,VIEW_PLATO_STATISTICS,GAMES_HISTORY,GAMES_STATISTICS,LOGOUT,
    // main menu
    SHOW_POINTS,VIEW_FAVORITE_GAMES,VIEW_PLATOBOTS_MESSAGE,VIEW_LAST_PLAYED,VIEW_ADMINS_SUGGESTION,ADD_FRIEND,CHOOSE_SUGGESTED_GAME,
    //admin menu
    ADD_EVENT,VIEW_EVENTS,ADD_SUGGESTION,VIEW_SUGGESTIONS,VIEW_USERS,
    //games menu
    OPEN_GAME,
    //friends menu
    SHOW_FRIENDS,SHOW_FRIEND_REQUESTS,
    //register menu
    REGISTER_USERNAME,DELETE_USERNAME,LOGIN_USERNAME,SHOW_SCOREBOARD,DETAILS,SHOW_LOG,SHOW_WINS_COUNT,SHOW_PLAYED_COUNT,ADD_TO_FAVORITE,RUN_GAME,SHOW_POINTS_GAME ;

}
