package view;

public enum  subMenuStatus {
    CHANGE_PASSWORD,EDIT_FIELD
    ,CHOOSE_SUGGESTED_GAME,
    EDIT_EVENT,REMOVE_EVENT,REMOVE_SUGGESTION,VIEW_USER_PROFILE,
    REMOVE_USERNAME,VIEW_USER_PROFILE_FMENU,
    ADD_USERNAME,ACCEPT_USERNAME,DECLINE_USERNAME ;

}
